server-deployment: add .Values.externalPort to customize EXTERNAL_PORT
kcp-dev/helm-charts pull request #88
Opened 2024-04-01 15:36 UTC by darkmuggle

Before this PR, the external port of the kcp server is set to 8443 for a `LoadBalancer` service type and 443 otherwise. The later is the case where an ingress is expected to be in-front of kcp. But when the actual usecase is to talk to the frontproxy directly via the service, this logic is wrong. Adding `.Values.externalPort` allows the customize the port, overriding upper logic.

2024-04-02 06:05 UTC, embik commented
Hi @darkmuggle, thank you for the contribution! Can you please give some more context on what bug you are seeing and what configuration triggers it?

The original idea here was to use port 443 if an `Ingress` is used to expose the front-proxy, since then access to it is not available on port 8443. Maybe the if condition here is faulty though and should be checking for that directly (and not for the service type).

2024-04-02 11:15 UTC, sttts commented
@mjudeikis compare https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/templates/front-proxy-deployment.yaml#L18. The frontproxy service uses also 8443, not 443. So to make the service work as entry-point the deployment must use 8443 also in non-LB mode.

2024-04-02 11:24 UTC, embik commented
> @mjudeikis compare https://github.com/kcp-dev/helm-charts/blob/main/charts/kcp/templates/front-proxy-deployment.yaml#L18. The frontproxy service uses also 8443, not 443. So to make the service work as entry-point the deployment must use 8443 also in non-LB mode.

But that is confusing to me because the `EXTERNAL_HOSTNAME` variable is set to Helm values' `.externalHostname`. That should be the external DNS name (so `kcp.beckers.dev`) usually (unless this is being used differently, which might be causin g the confusion) and not the `kcp-front-proxy.kcp.svc.cluster.local` service DNS name. 

For me there are two deployment scenarios:

1. You use the `LoadBalancer` service type. Then I get an LB from e.g. AWS, I set a CNAME on `kcp.beckers.dev` and my kcp front proxy endpoint is available as `kcp.beckers.dev:8443`.
2. You expose via Ingress or OpenShift Route. Then traffic flows through the ingress controller via HTTPS, which usually listens on port 443. So my kcp front proxy endpoint is available as `kcp.beckers.dev:443`.

As far as I understand, the point made is that there is a third option, where you don't expose kcp at all and just make it available via its front-proxy `Service` endpoint within the cluster. Is that correct? If so, we need to refine this PR because it will break scenario (1).

2024-04-02 11:43 UTC, sttts commented
Right, kcp is installed in-cluster and only accessed from there.

2024-04-17 07:39 UTC, embik commented
/ok-to-test

2024-04-17 07:41 UTC, embik requested changes

2024-04-17 07:41 UTC, embik commented on charts/kcp/templates/server-deployment.yaml
> +              value: {{ if eq .Values.externalPort "" }}{{ if eq .Values.kcpFrontProxy.service.type "LoadBalancer" }}8443{{ else }}443{{- end }}{{ else }}{{ .Values.externalPort }}{{- end }}
Needs the string wrapping back, else it's recognised as int.

2024-04-17 07:46 UTC, embik approved these changes
/approve

2024-04-17 07:47 UTC, merged